In [2]:
import time

start_time = time.time()
list1 = [x for x in range(1,100000)]
list2 = [y for y in range(1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()
print("Time taken by list concept", end_time-start_time)

Time taken by list concept 0.015609979629516602


In [5]:
import time
import numpy as np
start_time1 = time.time()
ar1 = np.array(list1)
ar2 = np.array(list2)
ar1*ar2
end_time1 = time.time()
print("Time taken by numpy is:", end_time1-start_time1)

Time taken by numpy is: 0.015625


In [10]:
d2 = np.array([[45,74,36],[96,87,69]])
d2

array([[45, 74, 36],
       [96, 87, 69]])

In [11]:
d2[0][1]

74

In [12]:
d2[0].min()

36

In [13]:
d2[0].max()

74

In [14]:
d2[0].sum()

155

In [15]:
d2[1].sum()

252

In [16]:
d2.sum(axis=0)

array([141, 161, 105])

In [20]:
for i in range(1,11):
    print(i,end = ' ')

1 2 3 4 5 6 7 8 9 10 

In [21]:
range(1,10,2)

range(1, 10, 2)

In [22]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [25]:
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
print(np.ones([5,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
